name: learn-github-actions-sub
run-name: ${{ github.actor }} is learning GitHub Actions Sub
on:
  workflow_run:
    workflows:
      - learn-github-actions
    types:
      - completed
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Sub Workflow"
  print_context:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
