name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  # push:
  workflow_dispatch:
jobs:
  check-deno-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "latest"
      - run: deno --version
